### PR TITLE
setup project

### PR DESCRIPTION
**Pull request by webbdm**

### CODE REVIEW

**Comment by webbdm** [comment]
Quiz Complete 👍 🌮

**Comment by zoeames** [comment]
remember that you have a markdown previewer for the readme - that way you don't have to make so many commits for one file

**Comment by zoeames** [comment]
@webbdm Nice job! 2 things to fix:  1.  lots of console.logs that need to be removed, 2.  when i add in a 4th car to your json it does not display at all.  i would guess it has something to do with how you are calculating the opening and closing row tags

**Comment by webbdm** [comment]
@zoeames 

Yes. My markdown editor has been crashing sublime every time it is opened so I used the GitHub interface directly which caused that crazy list of commits 😬 

I banished all the remaining console.logs to the shadow realm & fixed the row tag bug, so this should be good to go 👍

**Comment by zoeames** [comment]
looks good 👍

**Pull request merged**
